# pylint: disable=invalid-name
"""[contact module migration]"""
# Generated by Django 3.2 on 2022-05-18 10:11

from django.db import migrations, models
# pylint: disable=invalid-name


class Migration(migrations.Migration):
    """[contact module migration]"""
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
