# pylint: disable=invalid-name
"""[checkout module migration]"""
# Generated by Django 3.2 on 2022-05-16 09:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    """[checkout module migration]"""
    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
